---
title: "Interactivity I"
author: "Lucia Wang"
date: "2023-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### review last lecture - making websites

### plot.ly and dashboards for interactivity
```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

import data
```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |>
  select(
    borough = neighbourhood_group, 
    neighbourhood, stars, price, room_type, lat, long) |>
  drop_na(stars) |>
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

use `plot_ly()`. can pipe, but instead of aes just put ~, geometry involves a type of plot and mode
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) |>
  plot_ly(x= ~lat, y=~long, color= ~price, text= ~text_label,
          type = "scatter", mode = "markers", alpha=0.5)
```
can zoom in and pan and hover. or select only some of the graph, like in this boxplot

```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(y=~price, color = ~neighbourhood, type="box")
```

bar plot
```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x=~neighbourhood, y=~n, type = "bar", color= ~neighbourhood, colors="viridis")
```

ggplot converted to plotly scatterplot's quality not as good but can be done
```{r}
ggp_scatter = nyc_airbnb |>
  ggplot(aes(x=lat, y=long, color=price)) +
  geom_point(alpha= 0.5)

ggplotly(ggp_scatter)
```



